// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlykjvtxbyohneisyuzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZseWtqdnR4YnlvaG5laXN5dXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzU5NjAsImV4cCI6MjA3MjQ1MTk2MH0.j6tAdj46G4pQ0zEmZfbXoIyBx6aFX9omf3oS9Nf0fDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});